<article class="tm-product-card">
<div class="tm-product-card-media">
<div class="tm-ratio tm-ratio-4-3"><a class="tm-media-box" href="[field:arcurl/]">
<div class="tm-product-card-labels"><span class="uk-label uk-label-success">new</span>
</div>
<figure class="tm-media-box-wrap uk-background-cover" style="background-image: url([field:litpic/]);">
</figure></a></div>
</div>
<div class="tm-product-card-body">
<div class="tm-product-card-info">
<div class="uk-text-meta uk-margin-xsmall-bottom">[field:title/]</div>
</div>
<div class="tm-product-card-shop">
<div class="tm-product-card-prices">
<del class="uk-text-meta">¥ [field:price/]</del>
<div class="tm-product-card-price">¥ [field:trueprice/]</div>
</div>
<div class="tm-product-card-add">
<a href="./plus/posttocar.php?id=[field:aid/]" class="uk-button uk-button-primary tm-product-card-add-button tm-shine js-add-to-cart">
<span class="tm-product-card-add-button-icon" uk-icon="cart"></span>
<span class="tm-product-card-add-button-text">购买</span>
</a>
</div>
</div>
</div>
</article>