<li>
<div>
<a class="uk-link-muted uk-text-center uk-display-block uk-padding-small uk-box-shadow-hover-large" href="[field:arcurl/]">
<div class="tm-ratio tm-ratio-4-3">
<div class="tm-media-box">
<figure class="tm-media-box-wrap uk-background-cover" style="background-image: url([field:litpic/]);"></figure>
</div>
</div>
<div class="uk-margin-small-top">
<div class="uk-text-truncate">[field:title/]</div>
</div>
</a>
</div>
</li>