<li class="uk-background-cover " style="background-image: url([field:litpic/]);" align="center">
    <a href="[field:arcurl/]" title="[field:fulltitle/]">
        <div class="uk-overlay uk-overlay-primary uk-position-bottom uk-text-center uk-transition-slide-bottom">
            <h3 class="uk-margin-remove">[field:fulltitle/]</h3>
            <p class="uk-margin-remove">[field:info/]...</p>
        </div>
    </a>
</li>